# <<<<<<<<<<<<<<<< NUMPY LIBRARY >>>>>>>>>>>>>>>

### NumPy is an open source python library that provides support for multi-dimensional array and matrices.It also has functions for working in domain of linear algebra , fourier transform , and matrices.

## IMPORT NUMPY LIBRARY

In [2]:
import numpy as np
print("numpy is imported")

numpy is imported


## Creation of Array 
### 1-D Array

In [3]:
ls = [41,52,63,96,85,74,523,14,47,58,69]
ls

[41, 52, 63, 96, 85, 74, 523, 14, 47, 58, 69]

In [4]:
arr = np.array(ls)
arr             # 1D array

array([ 41,  52,  63,  96,  85,  74, 523,  14,  47,  58,  69])

In [5]:
arr[2]  # first_element_address + (data_type_size * index)

np.int64(63)

In [6]:
type(arr)

numpy.ndarray

### ndim :- returns dimension of array.

In [7]:
arr.ndim  # no of dimension

# [25,41,63]  -->  1D ARRAY
#  [[],[],[]]  -->  2D ARRAY   

1

In [8]:
arr.dtype

dtype('int64')

In [9]:
ls = [24,36,778,77,99,25,46,26,37.878,43.24,'sanjana']  #item

arr = np.array(ls)
arr

# flexibility

array(['24', '36', '778', '77', '99', '25', '46', '26', '37.878', '43.24',
       'sanjana'], dtype='<U32')

### dtype :- returns datatype of the array.

In [10]:
arr.dtype

dtype('<U32')

## Accessing elements from 1-D Array :-
### --> using slicing 
### --> using indexing 

In [11]:
arr[2]   # indexing

np.str_('778')

In [12]:
arr[2:5:2]      # slicing

array(['778', '99'], dtype='<U32')

In [13]:
arr

array(['24', '36', '778', '77', '99', '25', '46', '26', '37.878', '43.24',
       'sanjana'], dtype='<U32')

### size :- returns no. of elements present in the array.

In [14]:
arr.size

11

### len(array_name) :- returns no of elements present in the array.

In [15]:
len(arr)   #polymorphism    

11

In [16]:
arr

array(['24', '36', '778', '77', '99', '25', '46', '26', '37.878', '43.24',
       'sanjana'], dtype='<U32')

### linspace(a,b,no_of_elements) :- returns an array having the no_of_elements provided as argument in between [a,b]

In [17]:
np.linspace(1,8,5)      # in b\w 1-8 , 5 items

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

## RANDOM MODULE

### This module contains the functions which are used for generating random numbers. 

In [18]:
import random

### randint(a,b) :- returns a value in between a to b.

In [19]:
random.randint(1,10)

2

### random() :- returns a random value.

In [20]:
random.random()     

0.5034191498973773

In [21]:
ls = ['sanjana','neha','ishan','yasmeen','tamanna']
ls

['sanjana', 'neha', 'ishan', 'yasmeen', 'tamanna']

### choice() :- returns a random data from the provided list or aaray

In [22]:
random.choice(ls)

'yasmeen'

### choices() :- returns random no of elements provided in the arguments from the list.

In [23]:
random.choices(ls,k=3)

['yasmeen', 'sanjana', 'neha']

In [24]:
ls

['sanjana', 'neha', 'ishan', 'yasmeen', 'tamanna']

### shuffle(name_of_list_or_array) :- returns a same list or array but elements may be situated at different or same position.

In [25]:
random.shuffle(ls)

In [26]:
ls

['sanjana', 'tamanna', 'neha', 'ishan', 'yasmeen']

### randint(a,b,no_of_elements) :- creates a array by choosing values randomly in between a and b.

In [27]:
arr=np.random.randint(1,50,10)
arr

array([17, 45, 23, 25, 33,  4, 28, 34, 15, 17], dtype=int32)

## 2-D ARRAY CREATION 
### 2-D ARRAY --> List of 1-D Arrays --> [ [ ],[ ],[ ],....,[ ] ]

### --> Using randint() function.  randint(a,b,(no_of_rows,no_of_columns))

In [28]:
np.random.randint(1,50,(10,5))

array([[26, 28,  9, 32, 45],
       [33, 36, 36,  6, 43],
       [11, 24, 46,  9, 19],
       [45,  2, 13, 35,  9],
       [12, 17, 32, 37, 39],
       [19, 11, 36, 36, 15],
       [22,  5, 17, 34, 47],
       [44,  9,  8, 30,  6],
       [26, 30, 38, 23, 37],
       [41,  6,  4, 44, 24]], dtype=int32)

In [29]:
!python --version 

Python 3.12.2


### arange(no_of_elements) :- returns a 1-D array contains no of elements provided as a argument starting from 0 to provided number.

In [76]:
arr=np.arange(60)  # create a array having 60 elemnets starting from 0 to 59.
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

### --> Using reshape(no_of_rows , no_of_columns) :- It converts 1D array into a 2D array.

In [31]:
arr.reshape(12,5)    # 12 rows and 5 columns (12 X 5 = 60)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [32]:
arr.reshape(20,3)

# 60 --> 15*4,20*3,30*2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

### Using resize(name_of_array , (no_of_rows , no_of_columns)) :- converting 1d array into 2d array using same elements provided in the 1d array.

In [33]:
arr2 = np.resize(arr,(25,25))  
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [34]:
arr2.shape

(25, 25)

In [35]:
arr2.ndim

2

In [36]:
arr2.reshape(625,)  #25*25=625

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

### ravel() :- same as reshape().

In [37]:
arr2.ravel()  # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

### flatten() :- same as ravel

In [38]:
arr2.flatten()      # same as ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [39]:
arr = np.random.randint(5,50,100)
arr

array([18, 40, 30, 41, 36,  8, 24, 39, 43, 46, 25, 33, 16, 27, 47, 33,  7,
       22, 13, 32, 25, 12, 49, 21, 41, 17, 39, 38, 31, 36, 18, 26, 24, 32,
       26, 42, 18, 15, 16, 38, 34, 20, 43, 31, 12, 38,  7, 35,  5, 28, 22,
       49, 10, 17, 45,  9, 27, 44, 45, 36, 30,  6, 23, 18, 17, 15, 34, 44,
       43, 43, 30,  8, 44, 24, 45, 27, 30, 38, 33,  9, 26, 21, 41,  9, 33,
       44, 30, 38, 27, 35, 17, 28, 46, 40, 24, 35,  8, 45, 47, 47],
      dtype=int32)

### min() :- returns minimum value

In [40]:
arr.min()

np.int32(5)

### sum() :- returns sum of elements present in the array

In [41]:
arr.sum()

np.int64(2903)

### max() :- returns maximum value.

In [42]:
arr.max()

np.int32(49)

### mean() :- returns average of array.

In [43]:
arr.mean()

np.float64(29.03)

In [44]:
arr = np.random.randint(5,50,(3,2))
arr

array([[30, 31],
       [24, 26],
       [16, 13]], dtype=int32)

In [45]:
arr.shape

(3, 2)

### transpose(name_of_array) :- convert rows into columns and vice-versa.

In [46]:
np.transpose(arr)

array([[30, 24, 16],
       [31, 26, 13]], dtype=int32)

In [47]:
np.transpose(arr).shape

(2, 3)

### transpose = T

In [48]:
arr.T

array([[30, 24, 16],
       [31, 26, 13]], dtype=int32)

In [49]:
arr = np.random.randint(2,12,(10,5))
arr

array([[11, 10,  8, 10, 10],
       [11, 11,  8,  8,  3],
       [ 2,  7,  4,  5,  5],
       [ 8, 11,  4,  6, 11],
       [ 5,  8,  4,  6,  4],
       [ 9,  5, 11, 10, 10],
       [ 9,  3,  7,  9,  8],
       [ 4,  9, 10,  7,  7],
       [10,  9,  2,  7,  4],
       [ 2,  4,  9,  3,  8]], dtype=int32)

## Accessing elements from a 2-D array

In [78]:
arr[0]   # returns a 1-D array as a single element.

np.int64(0)

#### NEGETIVE INDEXING

In [51]:
arr[-1]

array([2, 4, 9, 3, 8], dtype=int32)

## Slicing in 2-D array [ slicing for rows , slicing for columns ]

In [52]:
arr[0:10,0:2]

array([[11, 10],
       [11, 11],
       [ 2,  7],
       [ 8, 11],
       [ 5,  8],
       [ 9,  5],
       [ 9,  3],
       [ 4,  9],
       [10,  9],
       [ 2,  4]], dtype=int32)

In [53]:
arr[0:,0:2]   # arr[0:,:2] OR arr[:10,:2]  same output

array([[11, 10],
       [11, 11],
       [ 2,  7],
       [ 8, 11],
       [ 5,  8],
       [ 9,  5],
       [ 9,  3],
       [ 4,  9],
       [10,  9],
       [ 2,  4]], dtype=int32)

In [54]:
arr[3:6,2:]

array([[ 4,  6, 11],
       [ 4,  6,  4],
       [11, 10, 10]], dtype=int32)

In [55]:
arr[0::2,0::2]

array([[11,  8, 10],
       [ 2,  4,  5],
       [ 5,  4,  4],
       [ 9,  7,  8],
       [10,  2,  4]], dtype=int32)

In [56]:
arr[-10:,-5:-3]

array([[11, 10],
       [11, 11],
       [ 2,  7],
       [ 8, 11],
       [ 5,  8],
       [ 9,  5],
       [ 9,  3],
       [ 4,  9],
       [10,  9],
       [ 2,  4]], dtype=int32)

## 3-D ARRAY CREATION 

### randint(a,b,(no_of_matrices , no_of_rows , no_of_columns))

In [57]:
arr = np.random.randint(2,50,(5,10,5))   # 3D ARRAY
arr

array([[[31,  3,  4,  2, 23],
        [12, 18,  8, 18, 24],
        [39, 29, 31, 37, 34],
        [43, 20, 13, 18, 28],
        [13, 15, 26, 26, 30],
        [23, 40, 29, 36,  8],
        [ 7, 47, 45,  4, 37],
        [ 9,  2, 30, 43, 24],
        [ 3, 31, 10, 16, 27],
        [ 2, 48, 25, 47, 39]],

       [[26, 22,  2,  3, 12],
        [38, 26, 10, 40, 43],
        [35, 16, 30, 38, 15],
        [24, 42,  7, 43, 14],
        [47,  5, 29,  4,  6],
        [ 8, 15, 11, 43,  5],
        [ 2, 20, 10, 42, 19],
        [42, 13, 40, 29, 37],
        [10, 43, 46, 24, 32],
        [13,  9, 15, 41, 10]],

       [[ 3,  8, 28,  4,  7],
        [15, 37, 37, 19, 23],
        [45, 39, 48,  8, 19],
        [19, 45, 37,  9, 23],
        [18, 22, 20,  8,  7],
        [43,  3, 21, 26, 45],
        [32, 30,  2, 36, 49],
        [19, 12, 20, 21, 47],
        [37, 21, 17, 25, 26],
        [ 4, 40, 40, 25, 36]],

       [[ 5, 29, 37,  5, 21],
        [29, 46, 32, 48, 22],
        [40, 36, 36, 22, 12],
    

In [58]:
arr.shape  # return output in the form of (Table , Row , Column).

(5, 10, 5)

In [59]:
arr.ndim

3

## Accessing elements from the 3-D array

In [79]:
arr[3]      # returns a matrix(2-D ARRAY) as a single element.

np.int64(3)

In [61]:
print(arr[:,9:,:])

[[[ 2 48 25 47 39]]

 [[13  9 15 41 10]]

 [[ 4 40 40 25 36]]

 [[25 32 38 43 23]]

 [[ 3  2 24 16  4]]]


In [62]:
arr = np.array([7,5,9])
arr

array([7, 5, 9])

In [63]:
arr.max()

np.int64(9)

### argmax() :- returns the index of maximum number present in the array.

In [64]:
arr.argmax()

np.int64(2)

### argmin() :- returns the index of minimum number present in the array.

In [65]:
arr.argmin()

np.int64(1)

In [66]:
arr.sort()
arr

array([5, 7, 9])

### argsort() :- returns the indexes of elememts in the sorted form.

In [67]:
arr.argsort()

array([0, 1, 2])

In [68]:
arr = np.random.randint(2,12,(10,5))
arr

array([[ 6, 11, 11, 11,  9],
       [ 3,  5,  4, 10, 11],
       [ 4,  4,  3,  9, 10],
       [ 8,  2,  2,  6,  7],
       [ 3,  9,  6,  8,  3],
       [ 4,  8,  5,  7, 10],
       [11,  6,  2, 11,  7],
       [10,  7,  2,  6, 11],
       [ 7,  9,  4,  8, 11],
       [ 7,  5,  7,  8,  7]], dtype=int32)

### unique(name_of_array) :- returns unique items present in the array.

In [69]:
np.unique(arr)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [70]:
arr = np.random.randint(2,250,200)
arr

array([ 25, 203, 204, 227,   7, 176,  92, 170, 197, 164, 163, 186, 234,
        80, 227,  34,  48, 144, 100,  63,  52,  95, 222,  44,  60, 110,
       171,  50, 222, 219, 146, 228, 206, 180, 225,  88, 221,  43,  29,
        36,   6, 202,  41, 102,  61, 239, 109,  89, 177,  59, 153, 237,
       171, 208,   9, 208,  86, 121,  41, 233,  10, 246, 105, 248, 199,
        32, 173,  12,  28, 203,  20,  94, 194,  69,   8, 217, 173, 219,
       189, 166, 189,  51, 141, 215,   3,  81, 115,  32, 152,  36,  99,
       172, 140, 237, 238, 227, 229, 169,  73, 139, 142, 168, 249, 213,
        61,  26,  93, 101,  95,  87,  74,  46,  45, 249,  36, 177, 121,
       178, 134,  16, 209, 130,  29, 123, 183, 228, 168, 242, 184, 180,
       207,  69,  13, 176,  17, 215,  96, 147, 116, 188, 204, 175, 223,
       178, 184,  41,  90, 140,  87,  29,  77, 175,  10,  63, 102, 169,
        12, 141,  39,  41,  40,  52,  16,  86,  58,  46,  93,  44, 195,
       120, 135, 210, 160, 215, 149, 123,  93, 176, 214,  34,  8

In [71]:
np.median(arr)

np.float64(134.5)

In [72]:
arr.var()

np.float64(5374.950975000001)

In [73]:
arr.std()

np.float64(73.31405714458859)

In [74]:
np.sqrt(25)

np.float64(5.0)